### ISSUE TITLE
Rename `X-Reactive-Auth` header.

### ISSUE THREAD

**Issue by beauby** [SkipLabs/skip#423] opened 2024-10-22 11:37 UTC
Following [RFC6648](https://datatracker.ietf.org/doc/html/rfc6648), we should avoid using the `X-` prefix. We could rename it to `Skip-Reactive-Auth`.

**Comment by bennostein** [comment] 2024-11-06 14:55
duplicate of #456 ; closed by #461

**Closed as completed by bennostein** 2024-11-06 14:55 UTC
